site_name: عنوان الموقع
docs_dir: docs
site_dir: public
site_url: https://siteurl.test/ #important if you want to generate sitemap.xml
repo_url: https://github.com/Extendy/mkdocs-arabic-skelton #use your GitHub repo url if there is linked repo or remove it to disable it
site_description: 'وصف'
site_author: 'Extendy Team'
copyright: 'Copyrights © 2024 Extendy Team'
nav:
  - الرئيسية: index.md
  - مثال على قائمة اساسية:
    - صفحة داخل قائمه: inner.md
  - استخدام الايقونات: icons.md   
  - رخصة الاستخدام: license.md
theme:
    name: material
    language: ar
    direction: rtl
    font:
      text: 'Rubik' # from google fonts https://fonts.google.com/ or remove it to use default font.
    palette:
    primary: light blue # see https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    features:
      - content.code.copy
      - content.code.select
      - navigation.tracking
      - search.share
      - search.suggest
      - navigation.instant
      - navigation.instant.progress
plugins:
  - search
extra:
  version: 0.0
  alternate:
    - name: English
      link: https://extendy.net/docs/en/
      lang: en
  generator: false
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      pygments_style: "monokai"  # Use a different style here
  - pymdownx.inlinehilite:
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
